---
old_domain: alpha.katuma.org
domain: app.katuma.org
rails_env: production

admin_email: info@coopdevs.org

mail_domain: katuma.org

certbot_domains:
  - app.katuma.org
  - alpha.katuma.org

certbot_cert_name: app.katuma.org

swapfile_size: 1G
